### ISSUE TITLE
Sort individual lists

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#100]
### Suggestion / Feature Request

The all list is sorted, sort the the other individual lists as well according to name

**Comment by Chandra-Sekhar-Bala** [comment]
Hey @ken1000minus7 are you saying sorting the list before providing it to the [ListAdapter](https://github.com/PEC-CSS/MovieDroid/blob/main/app/src/main/java/com/pec_acm/moviedroid/mainpage/list/ListAdapter.kt)  ?

**Comment by ken1000minus7** [comment]
Yup, the list should be sorted according to the title and then passed to the `ListAdapter`

**Comment by ken1000minus7** [comment]
Let me know if you want to work on this issue 😇

**Comment by Chandra-Sekhar-Bala** [comment]
Sure, I would love to help. Assign it to me @ken1000minus7.

**Comment by ken1000minus7** [comment]
Assigning u then

**Comment by Chandra-Sekhar-Bala** [comment]
Thanks @ken1000minus7  :)
