### ISSUE TITLE
Change status bar color

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#101]
### Suggestion / Feature Request

Change color of the status bar to match the app's theme

**Comment by rishabhknowss** [comment]
please assign me the task

**Comment by ken1000minus7** [comment]
Sure @rishabhknowss , good luck 😄

**Comment by PratikFagadiya** [comment]
Hey @ken1000minus7 can u assign me this task?

**Comment by ken1000minus7** [comment]
Sure @PratikFagadiya good luck !

**Comment by humaneBicycle** [comment]
sorry i dont understand which color you mean when you say app's theme. could you please explain? 

@ken1000minus7
