### ISSUE TITLE
Add a back button for back navigation in `ProfileActivity` and `AboutActivity`

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#103]
### Suggestion / Feature Request

Exactly what it says

**Comment by VSen910** [comment]
Hi! I'd like to take this up

**Comment by VSen910** [comment]
The default client id is supposed to be not there in the strings xml right?

**Comment by ken1000minus7** [comment]
@VSen910 assigning u 😇. Yeah that default web client id is generated during build
