### ISSUE TITLE
Add option to remove rating given to a movie/TV show

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#104]
### Suggestion / Feature Request

The score bottom sheet contains no option to remove rating, add an option for it. On removing the rating, score property of the user should be set to 0

**Comment by prasad-333** [comment]
I would like to contribute

**Comment by bharadwajmsr** [comment]
I have raised pull request https://github.com/PEC-CSS/MovieDroid/pull/131. Could you please check it?
