### ISSUE TITLE
Change the font of the application text

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#105]
### Suggestion / Feature Request

The default font is being used right now, would be nice to have good looking font, can check out google fonts for any good ones

**Comment by frey0-0** [comment]
assign this issue  to me @ken1000minus7 
would like to work on this but I might need some guidance

**Comment by ken1000minus7** [comment]
Sure @Frey0-0 , assigning u 😄

**Comment by shrishti147** [comment]
hi, please assign me.

**Comment by ken1000minus7** [comment]
Sure @shrishti147 go ahead 😇

**Comment by kashish0604** [comment]
hey @ken1000minus7 can you assign this issue to me i can work on it

**Comment by ken1000minus7** [comment]
Hey @kashish0604 , thanks for your interest in contributing but this issue is already assigned 😅 . You can check out other issues or create new ones that may be relevant 😇

**Comment by yellowHatpro** [comment]
@shrishti147 any updates🤔 ??

**Comment by armaanbadhan** [comment]
i would like to work on this issue, assign pls

**Comment by ken1000minus7** [comment]
Lfg
