### ISSUE TITLE
[Feature Request / Suggestion]: Add black gradient & elevation to card view

### ISSUE THREAD

**Issue by its-me-debk007** [PEC-CSS/MovieDroid#107]
### Suggestion / Feature Request

By adding black gradient to the title of the card view, and applying a little bit of elevation, makes the card view more visually appealing

Please assign me this task. Would be happy to contribute :)

![Screenshot_2022-10-22-11-38-47-763_com pec_acm moviedroid](https://user-images.githubusercontent.com/81604986/197323469-840c6f74-99fc-4038-9c20-b481567aa7fe.jpg)

**Comment by ken1000minus7** [comment]
Sure @its-me-debk007 go ahead, assigning u 😄
