### ISSUE TITLE
Create a Splash Screen

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#11]
Create a splash screen for the app

One of the ways of implementing a splash screen:-
https://stackoverflow.com/a/5486970/17369066

It is preferrable to make a design for the splash screen in figma before implementing it in xml

**Comment by karanpreet8082** [comment]
I would like to work on this issue.
Let’s put our heads/minds together.

**Comment by yellowHatpro** [comment]
> I would like to work on this issue. Let’s put our heads/minds together.

Ya sure why not 😄

**Comment by karanpreet8082** [comment]
Thank you sir very much for giving me a chance to showcase my skills.

**Comment by vishal2376** [comment]
Hi, I would like to work on this issue.

I can create a splash screen with implementation in kotlin.

**Comment by yellowHatpro** [comment]
Hello @vishal2376, thanks for your interest. Currently the issue is assigned to @karanpreet8082 , but you are free to explore other issues 😀✨

**Comment by Perumallpardhiv** [comment]
@yellowHatpro Can I contribute on this issue?
