### ISSUE TITLE
[Bug]: Wrong alignment of CardViews in the AllItems Fragment

### ISSUE THREAD

**Issue by its-me-debk007** [PEC-CSS/MovieDroid#110]
### Contact Details

debashish.joy@gmail.com

### What happened?

As we can see in the screenshot, the recycler view is aligned more to the left side, than to the center

![1666522598847](https://user-images.githubusercontent.com/81604986/197388900-4517c83b-54ae-495a-9f80-6f3abcb64baf.jpg)

### In which device are you seeing the problem on?

Phone, Tablets, Emulator

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by its-me-debk007** [comment]
Please assign this issue to me

**Comment by ken1000minus7** [comment]
Ok @its-me-debk007 assigning u 😇
