### ISSUE TITLE
Placeholder image in list item

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#112]
### What happened?

Add a placeholder image in the list item to display when the poster url is empty
![image](https://user-images.githubusercontent.com/78747188/197400711-8ccb332a-85b8-4fe1-8ab9-1d30f40a3bf1.png)
 

### In which device are you seeing the problem on?

Emulator

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rosita-dmello** [comment]
Hi.. I'd like to work on this issue. Can you assign it to me?

**Comment by Chandra-Sekhar-Bala** [comment]
Hey @ken1000minus7 is [this](https://img.freepik.com/free-vector/film-strip-background-with-clapper-board_1017-33456.jpg?w=1060&t=st=1666771209~exp=1666771809~hmac=83a06d22c9a4a5cba0aaf21375454e0bfc7e28742bc926cc263f70a238dbed9c) a good placeholder graphic?

**Comment by ken1000minus7** [comment]
I think something with a white background would look better 🤔

**Comment by Chandra-Sekhar-Bala** [comment]
How about [this](https://img.freepik.com/free-vector/cinema-film-elements-objects_1017-33459.jpg?w=1060&t=st=1666776002~exp=1666776602~hmac=0bad76d8c7597de36b42f2e5ecc789703723da4c777ff279a5bebdc66e610011)?

**Comment by ken1000minus7** [comment]
Seems good , I think we can work with just this part
![image](https://user-images.githubusercontent.com/78747188/198097345-9a916e86-98d1-4362-b5a3-0a2684f24190.png)
