### ISSUE TITLE
Change Toolbar color in detail fragments

### ISSUE THREAD

**Issue by yellowHatpro** [PEC-CSS/MovieDroid#115]
### Suggestion / Feature Request

Change Tv Detail Fragment and Movie Detail Fragment 's collapsing toolbar color to match app's theme.

**Comment by atharvabhoite7** [comment]
Hey @YoshithaRathnayake ! I'm interested in this. Please can you assign it to me?

**Comment by atharvabhoite7** [comment]
Hey @yellowHatpro ! I'm interested in this. Please can you assign it to me?

**Comment by ken1000minus7** [comment]
Assigning u @atharvabhoite7 , good luck 😇

**Comment by yellowHatpro** [comment]
Hello @atharvabhoite7 , any updates ?? 🤔 
If you need any help you can tell

**Comment by armaanbadhan** [comment]
hey @ken1000minus7 i am interested, can you please assign me?

**Comment by ken1000minus7** [comment]
Sure gl
