### ISSUE TITLE
Add a toolbar in All Items Fragment

### ISSUE THREAD

**Issue by yellowHatpro** [PEC-CSS/MovieDroid#117]
### Suggestion / Feature Request

Add a toolbar in AllItem Fragment, to show the name of the argument (Top Movies, Top TV Shows, Popular Movies, etc) and a back navigation button.

**Comment by Rarj** [comment]
hi @yellowHatpro , can you assign it to me? I will work with this issue.
thanks anw!

**Comment by yellowHatpro** [comment]
Hello @Rarj , you may work on this issue 😄 !

**Comment by Rarj** [comment]
hi @yellowHatpro , on it!

**Comment by Rarj** [comment]
hi @yellowHatpro , would you plz review my work?
if you have any concern, don't hesitate to discuss here.

thanks anw!
