### ISSUE TITLE
Improve the user list item layout

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#12]
Create a layout for the cards that will appear in the user list
For this, first create a design for the card in the figma workspace and then implement it in xml.

**Comment by ken1000minus7** [comment]
I have created a basic layout in 62381d3d19156b975ec73fc8373beca98f444ba5
This can be improved to make it more attractive

**Comment by vishal2376** [comment]
Hey, I would like to work on this issue.

**Comment by ken1000minus7** [comment]
Assigning you 👍 @vishal2376

**Comment by vishal2376** [comment]
@ken1000minus7  Is it necessary to use dimen? Or I can use dp/sp instead.

**Comment by ken1000minus7** [comment]
Yeah @vishal2376 , please use sdp and ssp instead of dp and sp as they are scalable according to the screen size 😇

**Comment by vishal2376** [comment]
> Yeah @vishal2376 , please use sdp and ssp instead of dp and sp as they are scalable according to the screen size 😇 

ok 🙂
