### ISSUE TITLE
[Bug]: Duplicate list of cast and crews

### ISSUE THREAD

**Issue by vishal2376** [PEC-CSS/MovieDroid#129]
### What happened?

When opening any movie/tv detail page, some duplicate cast is shown in the cast list

### On which device are you seeing the problem?

Phone

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by armaanbadhan** [comment]
thats because the same person is listed multiple times for different departments in the api response
![image](https://user-images.githubusercontent.com/66007619/221367326-988c5bc5-fa78-421c-9d2a-a62231bf407c.png)

**Comment by ken1000minus7** [comment]
Interesting, then we gotta handle the repetitions manually

**Comment by ken1000minus7** [comment]
By converting to set maybe, wanna work? @armaanbadhan

**Comment by armaanbadhan** [comment]
why not
