### ISSUE TITLE
Converting static strings to string resources

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#13]
Replace all the static strings in the codebase by creating string resource for each string in the strings.xml file

_How to create a string resource?_

Go to the strings.xml file and under the resources tag, add a resource in the following format
```xml
<string name="name of string res">"The value of string resource"</string>
```
Example:-
```xml
<string name="hello_world">"Hello World!"</string>
```

**Comment by Manny-op** [comment]
Is it okay if I try this issue?

**Comment by Sidahmed-ben** [comment]
hello @ken1000minus7 , the issue interrests me can you assign it to me please. Thank you 👍

**Comment by ken1000minus7** [comment]
Sure @Sidahmed-ben , good luck! 😄

**Comment by jyorien** [comment]
hi I would like to be assigned to this:)

**Comment by yellowHatpro** [comment]
Go ahead @jyorien 😀✨
