### ISSUE TITLE
Create a person details page

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#144]
### Suggestion / Feature Request

The page should open when tapping on any cast of a movie or tv show and should properly display all the details of the person
Use this endpoint
https://developers.themoviedb.org/3/people/get-person-details
Create data classes accordingly, the design of the page is upto innovation but all details should be displayed

**Comment by armaanbadhan** [comment]
id like to work on this

**Comment by ken1000minus7** [comment]
assigning
