### ISSUE TITLE
Implement ViewBinding in all Activities and Fragments

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#16]
Currently most of the activities and fragments use findViewById for accessing the views from the xml file. However, it is preferred to replace it with Jetpack ViewBinding to ensure type and null check and avoid unnecessary boilerplate code.

_What is ViewBinding and how to implement it?_

Refer the official android docs
https://developer.android.com/topic/libraries/view-binding

**Comment by Raveesh2324** [comment]
I would like to work on this issue.
