### ISSUE TITLE
Avoid Screen from getting dimmed

### ISSUE THREAD

**Issue by dhruv-porwal** [PEC-CSS/MovieDroid#163]
### Suggestion / Feature Request

Screen may get dimmed on not operation by user or whenever screen becomes unresponsive due to some interruption by system.

We need to avoid this issue.

**Comment by dhruv-porwal** [comment]
Please assign this issue to me.

**Comment by ken1000minus7** [comment]
Can u explain a bit on what u wish to achieve with this?

**Comment by dhruv-porwal** [comment]
> Can u explain a bit on what u wish to achieve with this?

Screen automatically gets dimmed whenever system interrupt occur or due to any possible system interrupt.

**Comment by ken1000minus7** [comment]
Can u clarify what do u mean by system interrupt? Maybe through a video or something?

**Comment by ken1000minus7** [comment]
Closing the issue for now since no updates
