### ISSUE TITLE
use shimmer effect in mainactivity while data loads

### ISSUE THREAD

**Issue by armaanbadhan** [PEC-CSS/MovieDroid#169]
here 
<img src="https://media.discordapp.net/attachments/1039826490247880764/1080835734551941171/Screenshot_2023-03-02-18-24-57-54_92460851df6f172a4592fca41cc2d2e6.jpg?width=314&height=662">

**Comment by armaanbadhan** [comment]
assign :smileinpain:

**Comment by ken1000minus7** [comment]
Hmm makes sense
