### ISSUE TITLE
Add a Navigation Drawer

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#21]
Add a navigation drawer that will show general options like profile, settings, log out. These options will be changed or implemented later 

Refer official android docs:
https://developer.android.com/guide/navigation/navigation-ui#add_a_navigation_drawer

**Comment by bharadwajmsr** [comment]
@ken1000minus7 I want to work on this issue. Could you please assign this issue to me?

**Comment by ken1000minus7** [comment]
Sure @bharadwajmsr , good luck ! 😄

**Comment by bharadwajmsr** [comment]
@ken1000minus7 Raised a PR https://github.com/PEC-CSS/MovieDroid/pull/29
