### ISSUE TITLE
Display the number of entries in each user list

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#22]
Display the number of entries in a user list just above the `RecyclerView` of that list. For example, if there are 3 items, you need to display '3 entries' just above the first item
![image](https://user-images.githubusercontent.com/78747188/165357818-da3bbb54-cac2-49bd-9ecd-29622ed910e0.png)

**Comment by bharadwajmsr** [comment]
@ken1000minus7  I want to fix the issue, can you please assign this issue to me? 

one doubt:
      Should the number of items in list be shown where ever the `com.pec_acm.moviedroid.mainpage.list.ListAdapter`is used?

**Comment by ken1000minus7** [comment]
@bharadwajmsr sure 😄
The number of items are to be displayed only above the 6 user lists, i.e. , in the `AllListFragment` , `WatchingListFragment` ,`CompletedListFragment` ,`OnHoldListFragment` ,`DroppedListFragment` and `PlanToWatchListFragment`.

**Comment by bharadwajmsr** [comment]
@ken1000minus7 Raised a PR https://github.com/PEC-CSS/MovieDroid/pull/26.
