### ISSUE TITLE
Create a pull request template

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#24]
Create a template for pull requests that will be created in this repo

**Comment by dylan-power** [comment]
Hi, I'd like to take this issue. Are there any guidelines for what you would like to see in the template? Thank you.

**Comment by ken1000minus7** [comment]
Hi @dylan-power 😄 , thanks for your interest in this issue. There is no specific guidelines that we have decided on for the template so you are free to show your creativity. Overall the template should contain at least the following

- Description of the pull request
- Issue that is resolved by it
- Screenshots if applicable

 Feel free to add any additional features to the template 😊 
 
 You can also work on an issue template (#15) after this if you wish to
