### ISSUE TITLE
Add search for Tv Shows using chips

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#27]
Currently we can only search for movies in the `SearchFragment`. Add chips below the search bar to select whether to search for movie or Tv Show. We can keep the movie chip as checked by default.

Chips in Material UI
https://material.io/components/chips/android#using-chips

**Comment by yellowHatpro** [comment]
oh u made issue about this
can i work on this please 🙏🏼  @ken1000minus7

**Comment by ken1000minus7** [comment]
> oh u made issue about this

ahb
