### ISSUE TITLE
Sort the user lists

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#32]
The items in the user lists need to be sorted according to the title of the item.
In the all list, the items should be sorted such that they appear in the order
<ol>
<li>Watching items
<li>Completed items
<li>On hold items
<li>Dropped items
<li>Plan to Watch items
</ol>

These items must be sorted within themselves, i.e., all the watching items must appear before all the competed items but they should appear in sorted order according to their title
Example:-
<img src="https://user-images.githubusercontent.com/78747188/168464338-1058b023-2e4f-458a-b6a7-7bbfa08c4abf.png" height = 500>

**Comment by abhishekpathak1** [comment]
I would like to work on this. Could you please assign it to me ?

**Comment by ken1000minus7** [comment]
Sure @abhishekpathak1 , good luck ! 😇
