### ISSUE TITLE
Add Lottie animations

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#33]
Add suitable lottie animations that should appear when search results are loading, movie details are loading and at any other relevant places.

https://lottiefiles.com/getting-started

**Comment by Devendra34** [comment]
Hi @ken1000minus7, 
I'm interested. Can you please assign it to me.. Also if you have a specific animation in mind, then please share it's link. Else I'll try to find out any suitable one. 
Thanks!

**Comment by ken1000minus7** [comment]
@Devendra34 assigning you 😇, there are no particular animations decided on yet, they just have to be suitable enough for the place they are used at. An animation for searching is already in the app, you can check that for reference if you want😊

**Comment by its-me-debk007** [comment]
Hi,
The developer seems to be inactive on this issue! Can I be assigned to this?

**Comment by ken1000minus7** [comment]
Ok sure @its-me-debk007 , assigning u 👍
