### ISSUE TITLE
Create App Icon

### ISSUE THREAD

**Issue by yellowHatpro** [PEC-CSS/MovieDroid#36]
- app icon needed

**Comment by karanpreet8082** [comment]
bhaiya bhaiya hamka chahiye wala

**Comment by karanpreet8082** [comment]
please assign it to me

**Comment by ken1000minus7** [comment]
Gl @karanpreet8082

**Comment by Perumallpardhiv** [comment]
@ken1000minus7 
pls assign this to me if it is not done at

**Comment by yellowHatpro** [comment]
@Perumallpardhiv thanks for you interest 😃😃, but currently the issue is assigned . But hey, you can explore the codebase and search for issues 😄

**Comment by Perumallpardhiv** [comment]
Sorry sir, I have just submitted the pr(before seeing this msg) by thinking
that It can be assigned
Forgive me sir, If I did any mistake, I am new to this github platform

**Comment by Perumallpardhiv** [comment]
And if possible once check my pr and pls say feedback
