### ISSUE TITLE
Improve the `SearchView`

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#37]
Currently the `SearchFragment` uses a basic search view which is not at all appealing, improve upon the design of the search view to make it similar to those present in most of the apps. Try to make the design relevant to its purpose, i.e., searching movies and TV shows

**Comment by neil0504** [comment]
Hello @ken1000minus7 , I would like to work on this issue. plz assign it to me.

**Comment by ken1000minus7** [comment]
Sure @neil0504 , go ahead 😇

**Comment by neil0504** [comment]
Hey @ken1000minus7 ,could you assign me again.

**Comment by ken1000minus7** [comment]
Ok 👍
