### ISSUE TITLE
Setup a basic onboarding in `LoginActivity`

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#40]
Add a basic onboarding to the `LoginActivity` initially consisting of three pages. They can remain empty for now as they will be filled with the appropriate content later. Along with this, the login functionality should be shifted to a fragment inside the `LoginActivity` instead of the `LoginActivity` so that onboarding can be used along with it.

**Comment by NiranjanNlc** [comment]
Hey , I am getting error at the                 .requestIdToken(getString(R.string.default_web_client_id)) line .
Would you please provide me the dummy ID ?

**Comment by shivamparihar12** [comment]
> Hey , I am getting error at the .requestIdToken(getString(R.string.default_web_client_id)) line . Would you please provide me the dummy ID ?

Hi @ken1000minus7, I'm facing the same issue. I need the Dummy ID too.

**Comment by ken1000minus7** [comment]
Hi @NiranjanNlc @shivamparihar12 😄 , that id is actually auto generated during build. Even though the line shows an error, the app should run without issues if you have set up firebase properly 😇 . Let me know if there are any issue while running the app 👍

**Comment by vishal2376** [comment]
I would like to contribute to this issue.

But I need some time to learn and implement onboarding because I don't know about the Onboarding screen and fragment navigation components.

It would be helpful if you can provide some resources

**Comment by ken1000minus7** [comment]
@vishal2376 You can get an idea about it through this video

https://www.youtube.com/watch?v=COZ3j8Dwlog

Let me know if you are willing to work on this issue 😇

**Comment by vishal2376** [comment]
Yes, assign me

**Comment by yellowHatpro** [comment]
Go ahead @vishal2376 😄

**Comment by HYnam** [comment]
Please assign this issue to me

**Comment by ken1000minus7** [comment]
Sure, gl

**Comment by HYnam** [comment]
Sorry :( can't figure it out

**Comment by ken1000minus7** [comment]
:( well, no prob, u can explore other issues

**Comment by armaanbadhan** [comment]
please assign

**Comment by ken1000minus7** [comment]
yes
