### ISSUE TITLE
Add colors for Night mode

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#41]
Add suitable colors for night mode in the night colors.xml file and corresponding light mode colors in the original colors.xml and use the colors wherever required. Each color in the night colors.xml should have the same name as their light mode counterpart in the original colors.xml. 

Like for example
In the original colors.xml
```xml
<color name="text_color">#000000</color>
```
Then subsequently in the night colors.xml
```xml
<color name="text_color">#FFFFFF</color>
```
<details> 
  <summary>PS</summary>
  This is just an example, all the colors of the app need to be added and not just this (probably don't even need to add this)
  </details>

**Comment by Dinoosawruss** [comment]
Hi, this sounds interesting could I be assigned?

**Comment by ken1000minus7** [comment]
Sure @Dinoosawruss , good luck ! 😄

**Comment by Dinoosawruss** [comment]
Have you got any specific reference to what kind of dark mode colours you might like or are you happy for me to explore?

**Comment by ken1000minus7** [comment]
You are free to explore what colors would look the best, there aren't any specific requirements for now 😇

**Comment by AndroidLion48** [comment]
Hello, may I please be assigned to contribute to your project?
I'm a new developer.
Thanks for participating in Hacktoberfest and providing this opportunity :)
