### ISSUE TITLE
Migrate `LoginActivity` to Kotlin

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#46]
Currently the `LoginActivity` is written in Java. Migrate the Java code to Kotlin.

**Comment by RahulSoni0** [comment]
can i contribute to this issue? @ken1000minus7

**Comment by ken1000minus7** [comment]
Sure @RahulSoni0 , assigning you 😇

**Comment by RahulSoni0** [comment]
hey @ken1000minus7 i'm getting Cannot resolve symbol 'default_web_client_id' , what to do 
<img width="820" alt="Screenshot 2022-10-01 at 2 04 09 PM" src="https://user-images.githubusercontent.com/75351409/193400834-a434f935-a11e-49c4-a47c-631767f67ab0.png">

**Comment by RahulSoni0** [comment]
can you once check on your local environment and fix it after that i will migrate it to kotlin , i have my kotlin code ready .@

**Comment by yellowHatpro** [comment]
Hello @RahulSoni0 , the id is generated at the build time. It won't affect the code in any way.

**Comment by ken1000minus7** [comment]
@RahulSoni0 you are free to make a pr if you are done with the migration, don't worry about the id 😇
