### ISSUE TITLE
Add Contribution Guidelines

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/MovieDroid#5]

**Comment by brunbs** [comment]
Hi, how can I contribute to this? =D

**Comment by Gauravsharma-20** [comment]
Hi, we need [Coding style](https://github.com/PEC-CSS/Open-Source#coding-style), [Making PRs](https://github.com/PEC-CSS/ACM-PEC-Website#making-prs) Guidelines and anything else you might think a new contributor should follow.
