### ISSUE TITLE
Migrate `CompletedListFragment` to Kotlin

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#50]
Java -> Kotlin pls, thank you 😇

**Comment by aakash232** [comment]
Pls assign this issue @ken1000minus7

**Comment by ken1000minus7** [comment]
@aakash232 Sure, good luck ! 😄

**Comment by aakash232** [comment]
@ken1000minus7 Pls review the PR#59. 
First contribution to this repo. Do let me know if any changes needed and pls guide me for the same.
