### ISSUE TITLE
Migrate remaining Java files to Kotlin

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#70]
### Suggestion / Feature Request

Let's remove java completely :) 

After migrating, remove the java badge from readme 😇

**Comment by krishnachaitanya0107** [comment]
Hi @ken1000minus7 

I would like to work on this , could you please assign it to me .

Thanks

**Comment by ken1000minus7** [comment]
Go ahead @krishnachaitanya0107 😋
