### ISSUE TITLE
Integrate Dagger Hilt

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#71]
### Suggestion / Feature Request

Integrate dagger hilt into the application and use it to inject the TMDB API instead of creating an instance of it

**Comment by krishnachaitanya0107** [comment]
Hi @ken1000minus7 

I would like to try working on this one , Could you please assign this issue to me .

Thanks

**Comment by ken1000minus7** [comment]
Sure @krishnachaitanya0107 , good luck! 😊
