### ISSUE TITLE
Redesign the App bar

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#72]
### Suggestion / Feature Request

Redesign the app bar to look something like this, the profile image of the user should be displayed in the circle on the right

![image](https://user-images.githubusercontent.com/78747188/193877696-3ac00198-c2ad-4be5-9ec1-bbc4eb691ea7.png)

**Comment by Miteshhsingla** [comment]
hey! I would like to contribute. Please assign this issue to me

**Comment by Miteshhsingla** [comment]
Do i have to code this app bar or only design a prototype?

**Comment by ken1000minus7** [comment]
@Miteshhsingla You have to implement the design in code and also add functionality for displaying the profile image of the user and openingthe navigation drawer. Assigning you 😇

**Comment by Miteshhsingla** [comment]
Sorry! I thought its only for designing purpose. You can re-assign it to somebody else.

**Comment by ken1000minus7** [comment]
Oh ok, no problem

**Comment by krishnachaitanya0107** [comment]
Hey @ken1000minus7 , 

I could try working on this one , Could you please assign it to me .

Thanks

**Comment by ken1000minus7** [comment]
Sure @krishnachaitanya0107 😇
