### ISSUE TITLE
Display pie chart of the count of different lists in `ProfileActivity`

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#79]
### Suggestion / Feature Request

Display a pie chart in the `ProfileActivity` showing the count of movies or tv shows with the  status
- Watching 
- Completed
- On Hold
- Dropped
- Plan To Watch

Use the corresponding colors of each list when representing them in pie chart

**Comment by armaanbadhan** [comment]
id like to

**Comment by ken1000minus7** [comment]
![](https://cdn.discordapp.com/emojis/884732267740659733.webp?size=128&quality=lossless)
