### ISSUE TITLE
Open `ProfileActivity` on clicking the profile pic

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#80]
### Suggestion / Feature Request

Open the `ProfileActivity` when user clicks on the profile pic on the app bar

**Comment by HeyRonak** [comment]
hello @ken1000minus7 can you please assign this issue to me ?

**Comment by ken1000minus7** [comment]
Sure, go ahead 😇 @ronakparmar533

**Comment by HeyRonak** [comment]
Thank you @ken1000minus7 for assigning this issue to me
