### ISSUE TITLE
Display list of cast and crew

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#82]
### Suggestion / Feature Request

Display list of cast and a list of crew of a movie or tv show in the detail fragments as a horizontal `RecyclerView`

**Comment by vishal2376** [comment]
I would like to work on it.

**Comment by ken1000minus7** [comment]
Assigning you @vishal2376 😇

**Comment by vishal2376** [comment]
Hi, I successfully fetched movie cast and crew data from API but I am a bit confused about the image. Here I am passing this path to the imageView.

profile_path = "/5XBzD5WuTyVQZeS4VI25z2moMeY.jpg"

How to get the image URL?

![image](https://user-images.githubusercontent.com/38159691/196051091-78bde1b3-8f37-4b06-b231-00b48be161be.png)

**Comment by ken1000minus7** [comment]
@vishal2376 you can use it like this

`https://image.tmdb.org/t/p/w138_and_h175_face/5XBzD5WuTyVQZeS4VI25z2moMeY.jpg`

Just add `https://image.tmdb.org/t/p/w138_and_h175_face` before the profile path

**Comment by vishal2376** [comment]
ok

**Comment by vishal2376** [comment]
@ken1000minus7 can i get your contact no. or any social handle?

**Comment by ken1000minus7** [comment]
can contact me on discord -> Ken1000minus7#2792

**Comment by yellowHatpro** [comment]
@vishal2376 any updates mate 🤔 ?

**Comment by vishal2376** [comment]
> @vishal2376 any updates mate 🤔 ?

movie cast implemented

only tv cast remaining

**Comment by vishal2376** [comment]
Done

**Comment by vishal2376** [comment]
Found a new bug #129 

I don't how it's happening 😅.
