### ISSUE TITLE
Add a remove from list option

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#83]
### Suggestion / Feature Request

In the `StatusBottomSheet`, add an option to remove the item from the user's list. Clicking on this option should open a dialog to confirm the removal

**Comment by krishnachaitanya0107** [comment]
Hi @ken1000minus7  ,

I would like to try working on this issue. Could you please assign it to me .

Thanks

**Comment by ken1000minus7** [comment]
Assigning you @krishnachaitanya0107 😄
