### ISSUE TITLE
Add Movie / TV Show videos in the detail fragments

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#84]
### Suggestion / Feature Request

Display the a list of different trailers and videos in the detail fragments as a horizontal pager where one can swipe or press on an arrow button (your choice which implementation you wanna go with, or you can implement both) to move to the next video

You can use [`YoutubeView`](https://github.com/PEC-CSS/MovieDroid/blob/main/app/src/main/java/com/pec_acm/moviedroid/mainpage/YoutubeView.kt)  in the layout to display a video, usage in kt file to display a video->
```kt
youtubeView.loadData(key, "text/html", "utf-8")
```
The videos and their keys can be obtained using [this api endpoint](https://developers.themoviedb.org/3/movies/get-movie-videos)

For now we'll stick ourselves to only youtube videos so ignore the videos which have `site` other than `"Youtube"`

**Comment by krishnachaitanya0107** [comment]
Hi @ken1000minus7  , 

i would like to try working on this issue . Could you please assign it to me .

Thanks

**Comment by ken1000minus7** [comment]
Sure @krishnachaitanya0107 , good luck 😊
