### ISSUE TITLE
Create an `AboutActivity`

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#85]
### Suggestion / Feature Request

The `AboutActivity` should display a brief info about this project and have a button to redirect the user to this github repo. An about should be added to the navigation drawer, which will be used to open this activity

**Comment by vishal2376** [comment]
Assign it to me

**Comment by RohitLakra299** [comment]
I want to work on this issue. Can you please assign this to me? @ken1000minus7

**Comment by neil0504** [comment]
Hey @ken1000minus7 , i would like to work on this issue if its available.

**Comment by ken1000minus7** [comment]
Assigning you @vishal2376 😄 

@RohitLakra299 @neil0504 Sorry but currently this issue is being assigned to the first person who commented 😅 , you can check out other issues for now or create any issue you find relevant. Thanks for your interest in contributing 😇
