### ISSUE TITLE
Fix text overflow in list item

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#88]
### What happened?

Limit the title to one line and show `...` at the end when the text exceeds the limit, also reduce the font size of the title a bit

![image](https://user-images.githubusercontent.com/78747188/194701455-9e4be3c7-3194-4e7d-959b-80dfdc862bb5.png)
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gautmikhanna** [comment]
assign it to me

**Comment by logicalahara** [comment]
Hey @ken1000minus7 , I've got a good grip over web tech and would be happy to contribute.

will you please assign this to me?

**Comment by ken1000minus7** [comment]
@gautmikhanna assigning you 😇 

@logicalahara thanks for your interest in contributing 😄 but currently I can assign this issue to only one person 😓 . You can try exploring other issues or create new ones, best of luck 😇

**Comment by humaneBicycle** [comment]
i cannot find this element anywhere is the app.

**Comment by ken1000minus7** [comment]
@humaneBicycle it's the `movie_list_item` layout

**Comment by Rarj** [comment]
Hi @yellowHatpro , is it still occur? Would you please assign this issue to me?
Thanks!

**Comment by yellowHatpro** [comment]
Hi @Rarj , yeah the issue is still open, you can continue working on this issue 😄

**Comment by Rarj** [comment]
on it!

**Comment by Rarj** [comment]
hi @yellowHatpro , would you plz review my work? 
if you have any question or advices, don't hesitate to discuss here.

thanks in advance!
