### ISSUE TITLE
Fix the text in the home page cards

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#92]
### What happened?

The text in the card should be centered, the font size is a bit small , need to increase that. Also, show ellipses `...` when the title overflows

![image](https://user-images.githubusercontent.com/78747188/194920698-fbdb5a48-57cb-4b48-bdfc-ff26d0a87ae2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by V9vek** [comment]
Hi @ken1000minus7 👋🏻 I would like to work on this. If this is open for contribution, please assign it to me.

**Comment by ken1000minus7** [comment]
Sure @V9vek go ahead 😄

**Comment by V9vek** [comment]
Hey @ken1000minus7, the project is building fine but when I tried to install it on device, it is showing me following error
![image](https://user-images.githubusercontent.com/40730402/195185536-2c55be02-3e1c-4768-b0a8-2268b1da892a.png)

**Comment by V9vek** [comment]
@ken1000minus7 I have opened the PR, kindly review it and if any changes are required, do let me know 😉

**Comment by ken1000minus7** [comment]
Oh, sorry for the late reply, is the error fixed? 😅

**Comment by V9vek** [comment]
Yes the error got fixed
