### ISSUE TITLE
Display average rating of user in `ProfileActivity`

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#94]
### Suggestion / Feature Request

Exactly what it says

Display 3 average ratings, overall, movies and tv shows

While calculating average ignore unrated movies or tv shows

**Comment by yashsarnaik22** [comment]
can I create cards to show the rating using html css and bootstrap?

**Comment by yashsarnaik22** [comment]
assign this to me, I can calculate average with some JS

**Comment by ken1000minus7** [comment]
Hey @yashsarnaik22 , this is an android application so we would prefer to have all functionality written using native android tech like kotlin rather than web tech like js 😅

**Comment by Chandra-Sekhar-Bala** [comment]
Hey @ken1000minus7 is that means we need to create two horizontal cards in profileActivity.  Then show 3 movies in one card, and tv shows on other, selected by average rating of 3-5 ?

**Comment by ken1000minus7** [comment]
You need to display the overall average score of all the items scored by the user in the user's list and below that u need to show two ratings, the average score given by the user of all movies in the user list and the average scoreof all the tv shows in the user's list. You do not have to display any movie or tv show

**Comment by armaanbadhan** [comment]
pls assign

**Comment by ken1000minus7** [comment]
Lessgo
