### ISSUE TITLE
Limit length of description in detail fragments

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#95]
### Suggestion / Feature Request

Limit the description to 4 lines in the detail fragments

Add a down arrow below the description to expand it

When expanded, replace the down with an up arrow to close it back

**Comment by Kardelio** [comment]
Hey @ken1000minus7 would you mind if i pick up this task?

**Comment by ken1000minus7** [comment]
Go ahead @Kardelio , good luck 😄

**Comment by Kardelio** [comment]
Thank you! @ken1000minus7 on it!

**Comment by Kardelio** [comment]
Is the Description in question the `overview` in `MovieDetailFragment` ?

**Comment by Kardelio** [comment]
@ken1000minus7 I have addressed this issue in PR: #96 
Please let me know what you think

**Comment by ken1000minus7** [comment]
> Is the Description in question the `overview` in `MovieDetailFragment` ?

Yes



> @ken1000minus7 I have addressed this issue in PR: #96 Please let me know what you think

Sure ✌️
